language: python
rvm:
  - 2.7.0

install:
  - wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_extended_0.80.0_Linux-64bit.deb
  - sudo dpkg -i hugo.deb

script:
  - hugo

deploy:
  # Cleanup removes keys and build artefacts.
  # See: https://docs.travis-ci.com/user/deployment/#Uploading-Files-and-skip_cleanup
  skip_cleanup: true
  provider: script
  script: tar -czhv -f www.tar.gz -C public . && bash -x .distributed-press/deploy.sh $api_key ./.distributed-press/config.json www.tar.gz
  on:
    branch:
      - master

notifications:
  email: false
